---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: set-img
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: set-img
rules:
- apiGroups:
  - ""
  verbs: ["*"]
  resources:
    - configmaps
    - namespaces
    - pods
- apiGroups:
  - "apps"
  verbs: ["*"]
  resources:
    - deployments
    - statefulsets

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: set-img-binding
subjects:
- kind: ServiceAccount
  name: set-img
  namespace: wu
roleRef:
  kind: ClusterRole
  name: set-img
  apiGroup: rbac.authorization.k8s.io
