name: ci
on:
  push:
    branches:
    - master
    - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1
      id: go

    - name: Get dependencies
      run: |
        go mod tidy

    - name: Test
      run: make run/test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1
      id: go

    - name: Get dependencies
      run: |
        go mod tidy

    - name: Build
      run: make build/main
