name: docker
on:
  push:
    tags:
      - '*'
jobs:
  docker:
    name: build and push image to docker hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out code 
      uses: actions/checkout@v1

    - name: buil and push 
      uses: docker/build-push-action@v1
      with:
        build_args: gitCommit=${{ github.sha }},semVer=${{ github.ref }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        
    - name: post to CI/CD webhook
      run: |
       curl "https://cicd.deoops.com/api/v1/auth/setdeploy/wu/image" \
        -X POST \
        -H 'Authorization: ${{ secrets.K8_CI_URL }}' \
        --data-binary '{"deploy_name":"set-img","container_name":"img","img":"${{ github.repository }}:${{ github.ref }}"}'

